#!/bin/bash
# This installs oh-my-zsh

WINDOWS_BASH_PATCH='@@ -2,6 +2,11 @@
 # see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
 # for examples
 
+# Launch Zsh
+if [ -t 1 ]; then
+exec zsh
+fi
+
 # If not running interactively, don'\''t do anything
 case $- in
     *i*) ;;
'
AGNOSTER_THEME_PATCH='@@ -7,7 +7,7 @@
 # Set name of the theme to load. Optionally, if you set this to "random"
 # it'\''ll load a random theme each time that oh-my-zsh is loaded.
 # See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
-ZSH_THEME="robbyrussell"
+ZSH_THEME="agnoster"

 # Uncomment the following line to use case-sensitive completion.
 # CASE_SENSITIVE="true"'

# (diff was generated using `diff -u <(cat original/file) <(cat final/file)`)

sudo apt-get -qq install zsh
echo installed $(zsh --version)

if grep --quiet --ignore-case -- 'Microsoft' <(uname --kernel-release); then
    # Windows always starts bash, so we must "redirect" `bash` to `zsh`
    # we'll do this by patching `/home/$USER/.bashrc`
    # https://www.howtogeek.com/258518/how-to-use-zsh-or-another-shell-in-windows-10/
    # http://www.thegeekstuff.com/2014/12/patch-command-examples
    echo "$WINDOWS_BASH_PATCH" | patch --forward --reject-file=- /home/$USER/.bashrc
else
    # This will set zsh as the default for the current user, and it's all that's
    # needed for "real" ubuntu
    # It's not very useful for bash on windows, as it'll start `bash` anyway
    chsh -s $(which zsh)
fi

# setup initial zsh profile
cp -n /etc/zsh/newuser.zshrc.recommended /home/$USER/.zshrc

# git is required by oh-my-zsh
sudo apt-get -qq install git curl

# install oh-my-zsh
# https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# changing theme to agnoster
echo "$AGNOSTER_THEME_PATCH" | patch --forward --reject-file=- /home/$USER/.zshrc

echo "All done! Get yourself a powerline compatible font if characters are looking weird"
